package:
    name: security_log_analysis
    version: "0.0.2.1"

#build:
    #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../

requirements:
  build:
    - python
    - numpy
    - libpython # [py2k and win]
    - sqlalchemy

  run:
    - python
    - numpy

test:
  imports:
    - security_log_analysis

  requires:
    - nose

  commands:
    - nosetests security_log_analysis

#about
  #home: http://pandas.pydata.org
  #license: BSD
